// a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('Verifier');

// Test verification with correct proof
// Test verification with incorrect proof
// - use the contents from proof.json generated from zokrates steps
contract('TestVerifier', accounts => {
    describe('Verify Tx', function () {
        beforeEach(async function () {
            this.contract = await Verifier.new({
                from: accounts[0]
            });
        });

        it('Correct verification', async function () {
            const {
                proof,
                input
            } = require('../../zokrates/code/square/proof.json');
            const verified = await this.contract.verifyTx.call(
                proof.A,
                proof.A_p,
                proof.B,
                proof.B_p,
                proof.C,
                proof.C_p,
                proof.H,
                proof.K,
                input
            );
            assert.equal(verified, true, "Not verified correctly");
        });

        it('Verifier captures wrong input', async function () {
            const {
                proof_err,
                input_err
            } = require('../../zokrates/code/square/proof-err.json');
            await expectThrow(this.contract.verifyTx.call(
                proof_err.A,
                proof_err.A_p,
                proof_err.B,
                proof_err.B_p,
                proof_err.C,
                proof_err.C_p,
                proof_err.H,
                proof_err.K,
                input_err
            ));
        })
    });
});

var expectThrow = async function (promise) {
    try {
        await promise;
    } catch (error) {
        assert.exists(error);
        return;
    }
    assert.fail('Expected an error but didnt see one!');
}